<a href="https://colab.research.google.com/github/Ashutosh9826/Machine_Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [529]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [530]:
dataset = pd.read_csv('train_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [531]:
print(X)

[['p' 't@' 'd' ... 'U' 'c,j' '*t,u']
 ['p' 'd@' nan ... '#u' 'O,I' 't,c']
 ['e' 'v' 'd' ... 'u' 'c,e' '&d,c']
 ...
 ['e' 't*' 'A' ... 'u' 'c,i' 't,u@']
 ['p' 'm@' 'd' ... 'u' '#c,j' 't,u']
 ['e' nan 'a' ... 'u' 'c,j*' 'l,u#']]


#Spliting features


In [532]:
dataset[['feature_21', 'feature_10']] = dataset['feature_21,feature_10'].str.split(',', expand=True)
dataset.drop(columns=['feature_21,feature_10'], inplace=True)
dataset[['feature_8', 'feature_15']] = dataset['feature_8,feature_15'].str.split(',', expand=True)
dataset.drop(columns=['feature_8,feature_15'], inplace=True)
dataset[['feature_1', 'feature_6']] = dataset['feature_1,feature_6'].str.split(',', expand=True)
dataset.drop(columns=['feature_1,feature_6'], inplace=True)

In [533]:
X = dataset.drop(dataset.columns[0], axis=1).values
y = dataset.iloc[:, 0].values

In [534]:
print(X)

[['t@' 'd' 'v*' ... 'j' nan nan]
 ['d@' nan 'v&' ... 'I' ' t' 'e ']
 ['v' 'd' 'T' ... 'e' 't' 'e']
 ...
 ['t*' 'A' nan ... 'i' '#t' 'e']
 ['m@' 'd' 't*' ... 'j' 'i' 'e&']
 [nan 'a' nan ... 'j*' ' a' 'e *']]


#Encoding

In [535]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), list(range(0, 22)))], remainder='passthrough')
X = (ct.fit_transform(X))

In [536]:
print(X)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [537]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [538]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25, random_state=0)

In [539]:
#print(X_train)

In [540]:
#print(y_train)

In [541]:
#print(X_test)

In [542]:
#print(y_test)

## Training the K-NN model on the Training set

In [543]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

#Pickle

In [544]:
import pickle

with open("classifier.pkl", "wb") as f:
    pickle.dump(classifier, f)

## Predicting the Test set results

In [545]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [1 0]]


## Making the Confusion Matrix

In [546]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[840  28]
 [ 64 742]]


#accuracy

In [547]:
accuracy_score(y_test, y_pred)

0.945041816009558

r^2

In [548]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7798652959943282